### ISSUE TITLE
Unable to login via Github

### ISSUE THREAD

**Issue by alnguyen** [vsankar7787/nabu#12]
Not sure if anything has changed recently (whether that's the github API) or perhaps 2-factor authentication being place, but I'm now getting the `Your Github Account does not belong to the Organization` error.

**Comment by vishysank** [comment]
I think this might have been because the access to the github api is broken specifically for welltok access. s github only issues tokens to a user not an org, and i was using one generated for my user for the env variable "GITHUB_API_ACCESS_TOKEN", and when i got removed from the welltok org, I deactivated all welltok related tokens, and that is probably why nabu is broken.
